### ISSUE TITLE
Add support for Ubuntu.

### ISSUE THREAD

**Issue by pateldevang** [sudnyeshtalekar/Whatsapp-Message-bomber#3]
Add screenshot and installation guideline.

**Comment by sudnyeshtalekar** [comment]
> Add screenshot and installation guideline.

**Comment by sudnyeshtalekar** [comment]
> Add screenshot and installation guideline.

There is no requirement of configuring firefo browser to function as webdriver.It works fine after the installation of web driver for firefox.
